### PR TITLE
IL 130: implement log in/ register support in app

### PR DESCRIPTION
**Pull request by bnelson777**
-Reformatted Login and Register components to match style of the rest of the app
-Implemented usage of bcrypt and rnsi for login encryption
-Implemented a listener that prompts user to login when app is put in the background
-Removed Login and Register components from home screen

Testing steps
1. Delete, npm install and rebuild app
2. Ensure that the first time app is opened you are prompted to set a password. 
  -Attempt to enter 2 passwords that do not match, ensure that the app does not allow you to move 
    forward
  -Enter two matching passwords and ensure the app permits you to the home screen
     **Important: Do not forget the password**
3. Minimize the app. Ensure the app prompts you to re-login when re-opened.
    (Minimizing the app is how the user is logged out)

**Note: Deep linking functionality currently not working with this ticket. We can either test and submit as is and do the deep link portion later, or complete the change by adding deep linking.**

### CODE REVIEW

**Review by joewetton — CHANGES_REQUESTED** [review]
Password needs to persist after app is force closed and reopened. As of now it only persists if the app is minimized.

**Comment by Nuni88** [comment]
@bnelson777 I'm getting this error when hitting register on both emulator and device:

regerror

I tried npm install, npm install isaac, and tried a react native link, but maybe I'm missing something for installing it.

As for the issue Joe mentioned, that might be because the salt isn't being saved into sensitive info and retrieved to be used in checking the password.

**Comment by bnelson777** [comment]
@joewetton I was having that same issue yesterday intermittently, something to do with the app state is off. I was planning on working on it more tonight.

@Nuni88  I thought that the compareSync() method in bcrypt took the attempted password and salted it for some reason. I'll have fiddle with it tonight. 

I knew my ticket had some bugs just wanted to get something up so you guys didn't think I've been slacking. ;) I'd like to get this mostly (pref. fully) done by tomorrow.

**Comment by bnelson777** [comment]
The errors you guys mentioned should be fixed now. Let me know if you guys are still having issues. gonna work on the deep linking now.

**Comment by bnelson777** [comment]
Reworking this to just show updated screens in dev links. Having problems with async support/screen navigation.

**Pull request closed without merging**
