### PR TITLE
IL-105: Message Box uses more space in the create_message component

### PR DESCRIPTION
**Pull request by vanctran**
New features:
* Create Message uses new AutoGrowingTextInput component

Test:
When creating a message, the text input box should grow with the message length.
There is a maximum length that the input box stops at and allows scrolling.

### CODE REVIEW

**Comment by bnelson777** [comment]
Having an issue where the text box blocks the sender receiver after text input, so the user is unable to change them. "Return" is also interpreted as "\n" so can't exit text box to change either. Maybe putting the text box in a separate container would help?

screen shot 2018-05-07 at 4 09 59 pm

**Review by bnelson777 — CHANGES_REQUESTED** [review]
see above

**Comment by Nuni88** [comment]
I think you could use margins in the style to make sure there's always a certain amount of space between the box and the selectors.

**Review by Nuni88 — APPROVED** [review]
create message box
This is how it looks for me on android. It's cramped, but it doesn't overlap.

**Review by bnelson777 — APPROVED** [review]

**Comment by bnelson777** [comment]
Everything now works and looking good 👍

**Pull request merged**
