### PR TITLE
Il-12: Register Component

### PR DESCRIPTION
**Pull request by vanctran**
- Added register component
- Added routes for register screen

### CODE REVIEW

**Review by joewetton — CHANGES_REQUESTED** [review]
1. Keyboard covers up register button, import keyboard spacer package and add it to your code can be found in 'new message' component.

2. When you type in a password the width is only 3 characters or so..

3. Login button should be named Register.

img_1099

**Comment by vanctran** [comment]
Sounds good @joewetton. I'll add that right now.

**Review by joewetton — APPROVED** [review]
👍 IOS

**Review by hontatfai — APPROVED** [review]
works on android emulator
test

**Pull request merged**
