### PR TITLE
IL-115: Implement android url scheme

### PR DESCRIPTION
**Pull request by Vancev**
Uses a redirection link set up by Joe since deep links aren't clickable on android. 

To test:
-Create a new message, email to yourself and click the link. The app should open and you should be taken to the decrypt screen with the information filled in. Click "decrypt" and message should be added to your inbox.

### CODE REVIEW

**Comment by joewetton** [comment]
I've tested this branch and it doesn't break IOS deep linking, however an android review is needed to actually test what this ticket is for.

**Review by joewetton — APPROVED** [review]

**Comment by ad25** [comment]
Tried this on two devices. Each time I click the link from email it open the app successfully, flashes the decrypt screen quickly, and goes back to home.

**Comment by joewetton** [comment]
@Vancev sounds like it's what you were telling me earlier was happening

**Comment by Vancev** [comment]
@ad25 If you rebuild the project does that still happen?

**Comment by ad25** [comment]
Rebuilding in android studio does fix it for me.

**Pull request merged**
