### PR TITLE
IL-109: Implement ios url scheme

### PR DESCRIPTION
**Pull request by joewetton**
- To test -
Compose new message, email it to yourself. Open the email tap on the idly:// link should open up the id.ly app and put it in the lockbox decrypt screen.

### CODE REVIEW

**Comment by joewetton** [comment]
FYI, this will only work for the IOS side, so android reviewer just make sure you can build and nothing looks broken :)

**Review by Vancev — APPROVED** [review]
Everything looks good. Builds on android

**Review by vanctran — APPROVED** [review]
Retrieved a message from email and it successfully puts it into our messages on iOS

**Comment by bnelson777** [comment]
Wow nice looks great 👍

**Review by bnelson777 — APPROVED** [review]

**Pull request merged**
