### PR TITLE
IL-157: Android suppress promise rejection warning

### PR DESCRIPTION
**Pull request by ad25**
Note: Deep link server may not be up at the moment. This ticket may break that.
 
# Testing
- Boot into the home screen using react-native run-android and ensure no warnings pop up.
- Create an identity on device 1
- Create an identity on device 2
- Share each identity between both devices
- Send a message from device 1 to device 2
- Open link in email, decrypt ,and ensure the message shows up in the message thread.

### CODE REVIEW

**Comment by hontatfai** [comment]
It doesn't pop up any yellow box while boot the app, but I couldn't test the rest without another device.

**Comment by Nuni88** [comment]
The warnings are gone now, but I can't test deep linking because of the domain expiration.

**Review by Nuni88 — APPROVED** [review]
Merged from master to fix the URL issue for deep linking and everything checks out on android.

**Comment by bnelson777** [comment]
Great work @ad25! I'll merge this as well as Jeff's after the presentation tonight, don't want any surprises during our presentation 😄

**Pull request merged**
