### PR TITLE
IL-41: we-write inbox logic to dynamically display threads based on messages available

### PR DESCRIPTION
**Pull request by joewetton**
- passes props to message_thread as sender/receiver public keys. 
- will dynamically update based on new messages being added/removed from the persistent storage. to test this try clear all and check the inbox, should be empty. 
-try to compose a message and tap done you should see a thread show up in the inbox.
- merged IL-39 into my branch to reduce chance of nasty branch conflicts

### CODE REVIEW

**Review by bnelson777 — APPROVED** [review]
This looks great @joewetton and @hontatfai! It's funny how just a small UI change can make such a difference. Also it's really exciting seeing the inbox logic working too!

I did get the below error only when I cleared all data. However I tested the inbox logic with the default data and it was fine. Not sure if this is something we should look into fixing since it's being generated from a dev function, but thought I'd report it anyway.
img_4539

**Comment by joewetton** [comment]
Ahh this is probably because my code doesn’t check for the case where there are not cards in props.cards this seems like an easy fix to implement.

**Review by vanctran — APPROVED** [review]
Works on Expo. I currently am using state over props for the message_thread. Once this is merged, I can call on your prop routing.

**Review by Vancev — APPROVED** [review]
Good on android

**Pull request merged**
