### PR TITLE
IL-144: Tweak image parameters for performance/quality

### PR DESCRIPTION
**Pull request by Vancev**
1. Before running the app, checkout master and add add this line under line 275 of create_card
`console.log("Size of original image: " + source.length);`
2. Run master and create a card. Add an image and make note of the image size from the log.
3. Checkout this branch and start the app. Create a new card and upload the same image as earlier.
4. Check the image size in the log. The new image size should be less than the original image size. 
5. Go to the card view and make sure the image quality looks sufficient.

### CODE REVIEW

**Review by bnelson777 — COMMENTED** [review]
Tested on my ios device and the changes no longer allow a photo to be uploaded when the user creates a card. Tried both from the camera roll and took a photo from the camera directly and neither time the pictures were added. However, user is still able to add a card without an image.

**Comment by Vancev** [comment]
@bnelson777 Did you run npm install?

**Comment by ad25** [comment]
Tested and works on android.

**Review by ad25 — APPROVED** [review]

**Comment by Vancev** [comment]
@bnelson777 I updated it to use existing libraries so you no longer need to run npm install. It should work for you now.

**Comment by ad25** [comment]
Tested again and works on android.

**Review by joewetton — APPROVED** [review]
Works on IOS, @bnelson777 can you double check if it works for you or not? Then it should be fine to merge.

**Comment by bnelson777** [comment]
@joewetton Sure testing now

**Comment by bnelson777** [comment]
@joewetton Hmmm I am still having the same camera issue. @Vancev I did run npm install yes, not sure why it's working for Joe and not me.

**Comment by bnelson777** [comment]
Got it working! Ok gonna merge this.

**Pull request merged**
