### PR TITLE
IL-75: Add share and new message button to card view

### PR DESCRIPTION
**Pull request by bnelson777**
-Added new buttons to card view

Testing instructions:
1. Choose card from wallet and from rolodex.
2. For each card verify buttons appear in card view.
3. Verify Share button leads to Share screen and Message button leads to new message screen.

### CODE REVIEW

**Review by vanctran — APPROVED** [review]
Works on iOS but doesn't set the values for the pickers on the create message screen. We could tack this onto the backlog.

**Comment by Nuni88** [comment]
@vanctran The branch I did that sets those default values hasn't actually been merged yet, so it won't work until then. Then we just need {recipient: this.props.card} in the create_message call here if @bnelson777 wants to add that.

**Comment by bnelson777** [comment]
@Nuni88 Sure I can do that

**Comment by Nuni88** [comment]
@bnelson777 Sorry, I actually realized while testing it that since card_view is the same for wallet and rolodex cards it needs a slight tweak for passing in. It should be sender instead of recipient if card.owner === true, and it should only be recipient when card.owner !== true. I'm adding in the code to accept a default sender in create_message now too on my IL-97 branch.

**Comment by Nuni88** [comment]
@bnelson777 Actually if you want, I could just fix what I'm talking about, because I realized there's another slight change needed too.

**Comment by bnelson777** [comment]
@Nuni88 Ok sure :)

**Review by Nuni88 — APPROVED** [review]
Works on android. Should be ready to work with IL-97 when it's merged now, too.

**Pull request merged**
