### PR TITLE
Il-26: Standardize JSON structure for message

### PR DESCRIPTION
**Pull request by joewetton**
- updated messages.json to reflect our changes discussed Wednesday

Note: to test this you will need to click the clear function in https://github.com/bnelson777/id.ly/pull/12  then open this branch to see the new message data loaded in the app.

### CODE REVIEW

**Review by bnelson777 — APPROVED** [review]
Looks good for ios

**Comment by ad25** [comment]
Tested in android emulator. Wallet and Rolodex both are consistent with cards.json.

Small issue: Time field in in the json is in seconds since epoch. Inbox uses milliseconds since epoch and shows a date from 1970. Should be a really simple fix though.
il25

**Review by ad25 — APPROVED** [review]
Tested in android emulator. Messages in inbox are consistent with messages in json.
Small issue: Time field in the json is in seconds since epoch. Inbox uses milliseconds since epoch. As a result, Inbox shows a date from 1970. As long as one standard is agreed upon, it should be a really simple fix in inbox.

**Comment by bnelson777** [comment]
Per Adrian's comment, creating an issue in Jira backlog to update from seconds to milliseconds

**Pull request merged**
