### PR TITLE
Login/Register components working on dev options

### PR DESCRIPTION
**Pull request by bnelson777**
Modified version of original IL-130

Login/Register components updated and password functionality working.

Testing
1. Change to dev mode
2. Set two different passwords for reg screen and ensure you get a prompt to re-enter.
3. Set the same passwords and make sure you get successful alert.
4. Go to login screen (also in dev mode) and enter incorrect password. Make sure error message pops up.
5. Enter correct password and make sure you are navigated back to home screen.

screen shot 2018-06-03 at 7 38 37 pm
screen shot 2018-06-03 at 7 38 48 pm

### CODE REVIEW

**Review by vanctran — APPROVED** [review]
Works on iOS.

One issue I see is the delay when submitting in both the registration and login screens. This also allows it to be submitted multiple times giving me a "passwords don't match" issue for the events after the first submission.

Great work by the way. I really like the UI and it fits into our color scheme perfectly.

**Comment by bnelson777** [comment]
@vanctran Thanks! I think the delay is part of what was actually screwing me up so much with the earlier versions because I'm pretty sure it was creating a race condition with the Asynchronous data. A loading animation or something might be a good idea, I'll work on adding one tomorrow 👍

**Review by hontatfai — COMMENTED** [review]
When I registered with the same password, it pops up the red screen. Is it expected?
reg

**Comment by Nuni88** [comment]
That's the same error I was getting before. I haven't tested this branch yet, but maybe that isaac library doesn't work with Android or has to be installed in some specific way?

**Comment by bnelson777** [comment]
@hontatfai  @Nuni88 No not expected lol. I thought it was isaac too so i removed it from this version. Not sure what the issue is this time but i'll do some checking.

Edit: Think I found the fix. Should have a new version up in about an hour

**Comment by bnelson777** [comment]
Well what I thought would be a quick fix led me deeper down a rabbit hole than I thought. I think I'll have to push it up later tonight.

**Comment by bnelson777** [comment]
Alright so long story short I'm not sure what's the problem for Android. There are a few things that I've come across that I've tested out but whenever I make the changes it seems to break the iPhone side. So since I can't test on Android and this is going to stay in dev mode anyway I'm just going to put some comments in, call it good and merge it.

**Pull request merged**
