### PR TITLE
Il-24: Normalize styles

### PR DESCRIPTION
**Pull request by ad25**
* Created initial base style definitions in app/styles/common.js
* Created a folder for each component
* Renamed component/<name>.js to component/index.js as prescribed in the format
* Created new file styles.js in each component directory
* Moved stylesheets from index.js into styles.js
* Imported component styles.js into component index.js
* Imported styles/common.js into each components styles.js
* Removed stylesheet import from component modules. (not necessary since stylesheets are declared in styles.js)
* Changed each components imports to be consistent with new directory structure
* Added style definitions to app/styles/common.js based on common fields in existing component styles
* Modified component styles to use common.js defintions where original style is still preserved

### CODE REVIEW

**Review by bnelson777 — APPROVED** [review]
Works for ios. I wasn't sure how I felt at first about renaming all the files to components/<xyx>/index.js. At first I thought that would kind of be confusing but after thinking about it I think it's a much better change. If we have to import anything from a file we are still importing the component by it's own name, so referencing the index.js files really only matter in the headers. The style system does seem a bit convoluted for our purposes -- I think this setup is more designed for projects that reuse a lot of basic components -- not necessarily where we're at yet, but once we get to the point where we are doing that it'll be an easy transition.

**Comment by Vancev** [comment]
I'm getting this error on android when I try to share a card from the wallet

30652995_1771283729558797_3686264142601125888_n

**Comment by bnelson777** [comment]
Just re-checked, I'm getting that error too. However, since there are merge conflicts on this branch I'm wondering if the error would be resolved by resolving the merge conflicts (this is happening on files that @joewetton recently updated).

**Comment by joewetton** [comment]
yep, this issue isn’t on master.

I think we need to make a habit of merging latest master into our pull requests from now on before we test.

**Comment by joewetton** [comment]
Need an ios/android check for my merge resolves, then should be good to merge

**Comment by bnelson777** [comment]
Working on ios for me 👍  (thanks @joewetton for fixing the merge issue)

**Review by Nuni88 — APPROVED** [review]
Works on android.

**Pull request merged**
