### PR TITLE
 IL-17: Create Message

### PR DESCRIPTION
**Pull request by Nuni88**
- Added CreateMessage component and associated files.

- Added dummy button on home screen to access create message screen.

Issues:

- Component does not yet check for a default recipient.

- Recipient dropdown menu currently displays all cards, not just rolodex cards.

- create_message/index.js line 95 makes text input box cleaner, but probably won't work on iOS. If it doesn't work, the line can be deleted.

### CODE REVIEW

**Review by bnelson777 — APPROVED** [review]
Works for ios, create message inbox isn't appearing per the issue you mentioned. I think we should probably delete it for now personally.

**Review by joewetton — CHANGES_REQUESTED** [review]
Need to add a "from:" dropdown as well here, as we have support for multiple card identities in this app, a message will have a public key from the users wallet associated with it. 

Similar to how an mail system with multiple emails allows you to pick which one to send an email from (business/personal etc.)


Also, when keyboard is up on IOS I can't see what is being typed in the text field.
img_0eca834becac-1

There is a handy package for react native that solves this. Example - https://github.com/joewetton/redux-boilerplate/blob/master/app/components/new_message.js#L157

**Comment by Nuni88** [comment]
Fixed issues mentioned in Joe's review.

**Review by joewetton — APPROVED** [review]

**Comment by joewetton** [comment]
changes look good, made issues for backlog to work on next sprint
https://ssid-psu-capstone.atlassian.net/browse/IL-42
https://ssid-psu-capstone.atlassian.net/browse/IL-43

**Review by Vancev — APPROVED** [review]
Looks good for android

**Pull request merged**
