### PR TITLE
IL-120: Flipped read/unread color schema

### PR DESCRIPTION
**Pull request by hontatfai**

### CODE REVIEW

**Comment by vanctran** [comment]
Works on iOS.

I'm not a huge fan of the light blue. My personal preference is the original grey color that you originally had it as.

**Comment by joewetton** [comment]
Maybe we can make a poll and switch it back to grey then, I don't really care the unread color, it was just driving me nuts that white was unread and grey was read.

**Comment by hontatfai** [comment]
yea, I thought grey is better than blue too.

**Review by Vancev — APPROVED** [review]
Works on android

**Comment by bnelson777** [comment]
Gonna go ahead and merge this since we have more than enough approvals. I like grey personally but we can make a small ticket out of it if everyone really wants to change.

**Pull request merged**
