### PR TITLE
IL-67: Replace Picker on create_message and create_card components

### PR DESCRIPTION
**Pull request by Nuni88**
- Removed Picker from create_message and create_card.

- Added ActionSheet to replace Picker.

- Modified UI to better fit with new selection menus.

### CODE REVIEW

**Review by joewetton — CHANGES_REQUESTED** [review]
screen shot 2018-04-29 at 1 58 19 pm

Works on IOS.. but I'm a little concerned with using pictures as UI elements when it takes a solid 30 seconds for these things to show up, could we make these a text "+" "Select Card" instead? Other then that, looks good.

**Comment by bnelson777** [comment]
I actually removed the picker from the create card screen with my changes:
https://github.com/bnelson777/id.ly/pull/61
Sorry I didn't realize how closely-related our tickets are. We could work on combining/optimizing our changes based on whatever's easiest. There will probably be more merge conflicts on the way with mine since I completely redid the UI for create_card...

**Comment by Nuni88** [comment]
@bnelson777 I don't think it will be too much of a problem. If we want to go with your display method then my changes to create_card can be ignored, and if we want to go with my method, then we'd just need to copy in the action sheet and change the onpress for the picture to point to the function to display the action sheet instead.

**Comment by bnelson777** [comment]
@Nuni88 If it's all the same to you I'd like to keep my changes then. 😁 I'm not sure if one of our methods is optimal over the other but if so I'm willing to adapt my code to match! Sorry again for the extra work!

**Comment by Nuni88** [comment]
I replaced the select card icon with a + in text instead for now since we're having the image loading issue. I don't think we should shy away from using images purely based on that, though, because we have to fix that issue regardless.

**Review by joewetton — APPROVED** [review]

**Comment by vanctran** [comment]
Works on Android

**Review by vanctran — APPROVED** [review]
Works on Android

**Pull request merged**
