### PR TITLE
IL-132: Pressing the input box does not allow you to go back out to select sender/recipient in create_message

### PR DESCRIPTION
**Pull request by Nuni88**
- Touching outside of the text input box in create_message should now dismiss the keyboard.

Testing:

1. Go to create message screen.
2. Tap text input box to bring up keyboard.
3. Type text in box and tap elsewhere on the screen. The keyboard should be dismissed.
4. Ensure other functionality is unaffected by selecting a recipient and sender and sending the message.

### CODE REVIEW

**Review by bnelson777 — COMMENTED** [review]
The input box issue is resolved however having an issue on both my device and simulator. (Were both blocked before? I can't remember...) When you input a message into the text box you can't go back to change the sender, receiver still can be changed though.

img_4571
img_4572

**Comment by ad25** [comment]
Works without issue on android(device and emulator).

**Review by ad25 — APPROVED** [review]

**Comment by Nuni88** [comment]
@bnelson777 I pushed up a change that I think should fix the problem. It seems to be a bug with the formatting that was probably always there but couldn't be seen because the keyboard couldn't be dismissed before.

**Review by joewetton — APPROVED** [review]
IOS 👌

**Comment by bnelson777** [comment]
Looks like @joewetton beat me, was literally about to write a review haha. Was gonna say the new changes don't seem to have an impact for me, still having the same issue with the sender. I am on a SE though so this may be an issue with smaller phones only?

**Comment by joewetton** [comment]
@bnelson777 checking on my SE

**Comment by joewetton** [comment]
@bnelson777 Ok so I pushed a small commit change, can you try it now? You should be able to tap outside the input box.

**Comment by bnelson777** [comment]
Works on my SE now 👍  Merging

**Pull request merged**
