### PR TITLE
IL-56: Deleted the space at top and made the whole page's color to white

### PR DESCRIPTION
**Pull request by hontatfai**

### CODE REVIEW

**Review by ad25 — APPROVED** [review]
Looks good on android.

**Review by bnelson777 — CHANGES_REQUESTED** [review]
img_4540
I'm getting the above error on this change. Seems like it may be a conflict with redux somewhere. Here is a link to a similar issue: https://github.com/infinitered/ignite/issues/1225 It may have some tips, otherwise I can help look more into it tomorrow.

**Comment by bnelson777** [comment]
I'm actually getting this issue on the master branch too so guess it's not your change that's doing it..

**Comment by hontatfai** [comment]
@bnelson777 did you update the RNRF? The latest RNRF will cause the issue.

**Comment by bnelson777** [comment]
@hontatfai no I don't think so, I'm just using the version have in our master/packages.json, I would have to explicitly update it right?

**Comment by hontatfai** [comment]
@bnelson777 you may try to delete the node_modules and expo these two files, and do 'npm install' to build up again, but just make sure that the version RNRF is "react-native-router-flux": "^4.0.0-beta.28" in the package json.

**Comment by bnelson777** [comment]
@hontatfai Thanks, i'll give that a shot! I have to leave here soon so probably won't be able to see for sure until tonight. I'm checking to see if any of the other ios testers have the same problem also.

**Comment by bnelson777** [comment]
@hontatfai I followed your suggestion and it's working on master! :) I'm going to test your branch again now.

**Review by bnelson777 — APPROVED** [review]
Looks good on ios, the earlier error was due to a problem with my machine setup

**Pull request merged**
