### PR TITLE
Il-25: Standardize JSON structure for card

### PR DESCRIPTION
**Pull request by joewetton**
- updated cards.json to reflect "card" instead of "cards" and also added fields we discussed Wednesday.

- updated inbox component to use these new fields changed

- updated share component to omit private keys and image (the image string is too big to fit in QR code) we won't be able to share image in cards to others until we get bluetooth functioning.

- added clear function, this will wipe the AsysncStorage of the device/emulator you are testing on and when you reload the app it will read in the cards.json file. This may stay a development feature or we may want to offer users a way to completely start their wallet over again, either way it will remain on the home screen for the time being as it's needed for development. Adding this button also required adding some missing redux functions and imports in the home component.

testing note: 
click
"[dev] Clear All Data" then reload to see the new json structure reloaded into the app.

### CODE REVIEW

**Review by bnelson777 — APPROVED** [review]
Looks good for ios

**Comment by ad25** [comment]
Tested in android emulator. Looks good.
il26

**Comment by ad25** [comment]
Tested on android emulator. Looks good. Wallet, Rolodex, and Inbox all show consistencies with data in cards.json.
il26

**Review by ad25 — APPROVED** [review]
Tested on android emulator. Wallet, Rolodex, and Inbox all show consistencies with data in cards.json.

**Pull request merged**
