### PR TITLE
IL-16: Lockbox

### PR DESCRIPTION
**Pull request by joewetton**
- added Lockbox component
- changed messages and card data to better reflect how data will look when adding cards/messages all Id's are unique, and each card has a working private/public key for us to test with!

Because Id's are now unique between messages and cards, the inbox logic will need to be rewritten I made a ticket in the backlog for this
https://ssid-psu-capstone.atlassian.net/browse/IL-41

until this ticket is done the inbox will not display card data properly.

### CODE REVIEW

**Review by bnelson777 — APPROVED** [review]
Looks good on ios 👍

**Comment by Vancev** [comment]
I get this error on android, but it still seems to work fine when I dismiss it. 

30726400_1774071602613343_2110909454558953472_n

**Comment by Nuni88** [comment]
I get the same issue as Vance. That font seems to be iOS only.

**Comment by joewetton** [comment]
@Nuni88 @Vancev give it a try now

**Comment by Nuni88** [comment]
@joewetton It looks like regular Helvetica isn't supported either. [This](https://stackoverflow.com/questions/19691530/valid-values-for-androidfontfamily-and-what-they-map-to?rq=1) page looks to have a list of supported font families.

**Comment by joewetton** [comment]
I'm a bit surprised Android doesn't support Helvetica.. haha but sans-serif will have to do.

**Review by Nuni88 — APPROVED** [review]
Works on android now.

**Comment by bnelson777** [comment]
image-1
I just reran the master branch and got the same error as the android testers except with 'san-serif'. However like they said the lockbox works fine when we dismiss it. Not sure if this is a cross-system bug or what but since it works for android and only requires a dismiss for ios (and also since it's already merged), I'll make a jira ticket.

**Pull request merged**
