### PR TITLE
IL-150: Scale elements based on screen size

### PR DESCRIPTION
**Pull request by Nuni88**
- Most text and UI elements are now scaled to the screen size rather than being a fixed size.
- Some elements remain unchanged as their fixed sizes are unlikely to cause issues with different screen sizes. These elements are the dev menu, the lockbox, and the inbox.
- The login and register components will not be able to have their display size normalized until IL-130 is merged.

Testing:
1. Go to each screen in the app and verify that all UI elements look good and more or less the same as before. There may changes to the size of some elements, but the proportions should be basically the same as they were.

### CODE REVIEW

**Review by joewetton — CHANGES_REQUESTED** [review]
Few UI issues when things get scaled to bigger screens like my iPhone X. The text appears a bit too big and portraits are wonky now/not displaying.
img_1319
img_1323
img_1321
img_1320
img_1318

**Comment by joewetton** [comment]
For reference here is the normal text size on the X. perhaps the multipliers aren't quite right? 
img_1324

**Review by hontatfai — APPROVED** [review]
Works on Android emulator

**Comment by joewetton** [comment]
I’ll check these changes on my X when I get off work. Till then please don’t merge.

**Comment by bnelson777** [comment]
I'm doing some comment merges that are probably going to affect some files in this branch. Let me know once finished and I'll resolve any merge conflicts.

**Comment by Nuni88** [comment]
I updated the fix to the card_view bug to make it look better, but I'm not really satisfied with this branch. Lowering the font size multiplier made the font size look better on a big device, but it's really tiny on my small phone, and I'm not sure if the scaling changes that are included in the branch will conflict with the things that aren't being scaled. I'll leave it up to you guys whether you want to merge it or not, but I'm also going to open a pull request for a branch that just fixes the card_view bug to use if we don't merge this.

**Comment by bnelson777** [comment]
I feel like you did a lot of otherwise good work on this branch so if we have to leave some items fixed that's fine as far as I'm concerned. We can make separate branches for bugs (font size, card view ) -- can you just revert those changes back to the old version and we can merge what you have?

**Comment by Nuni88** [comment]
I pushed up some changes to remove the bug fix from this branch and remove the font scaling.

**Review by joewetton — APPROVED** [review]

**Comment by joewetton** [comment]
Removing the fonts seems to have resolved my issues with this branch.

**Comment by bnelson777** [comment]
Hey @Nuni88 just so you know I created a new branch for your changes: https://github.com/bnelson777/id.ly/tree/IL-150-conflicts-resolved

This was part of my own screwing up with resolving conflicts so I basically had to just recheckout an older version and put it on a new branch. I will commit the new branch after our presentation tonight and close this one. Great work! Sorry for taking so long getting this corrected!

**Comment by Nuni88** [comment]
@bnelson777 No problem, sounds good!

**Comment by bnelson777** [comment]
Changes moved to this branch:

https://github.com/bnelson777/id.ly/pull/150

Closing this PR and merging other.

**Pull request closed without merging**
