### PR TITLE
IL-73: Make pictures in wallet/rolodex circular

### PR DESCRIPTION
**Pull request by Nuni88**
- Changed the styling in card_list to make avatars circular.

### CODE REVIEW

**Review by ad25 — CHANGES_REQUESTED** [review]
Having issues on both device and emulator. Repeatedly entering and exiting Rolodex will sometimes render non-circular images. Happens for Wallet as well. Not really sure why.

il73issue

**Review by hontatfai — COMMENTED** [review]
I wait few minute, it couldn't load the images. I am not sure that is it my interest issue.
wallet_test
rolodex_test

**Comment by Nuni88** [comment]
I'm kind of at a loss for what's causing these issues, because all I really did was set the border radius to 100 for the image. I've been able to replicate the issue with the images still being square, but haven't run into the other. I think the issues might be related to the general slow image loading problem we're having.

**Comment by Nuni88** [comment]
I think I've actually fixed it now. It seems that the 'contain' image mode doesn't play well with border radius, but 'cover' should work.

**Review by ad25 — APPROVED** [review]

**Comment by ad25** [comment]
Issues fixed for me on android.

**Review by bnelson777 — COMMENTED** [review]
I've tested in both an ios device and simulator and having the same issues as @hontatfai :( I @Nuni88 may be right in that this could be related to our slow image loading issue. We may need to think about putting this request on hold until we figure that problem out. Are you having the same issues @joewetton & @vanctran ?

**Comment by joewetton** [comment]
screen shot 2018-04-29 at 10 58 50 pm

I can't even get icons to load, same on device.

**Comment by joewetton** [comment]
Not trying to through too much of wrench into the work already done but maybe we can explore the idea of using a framework that inbox uses since it seems to not have the problem? Maybe we could tack this onto sprint 5.

**Comment by Nuni88** [comment]
I'm really not sure why it's not showing the images. I can't replicate the issue at all; they load instantly or near instantly on both my phone and the simulator. I did look into the slow image loading thing a little though, and it sounds like it might be just an expo problem.

**Comment by bnelson777** [comment]
@Nuni88 Lets just leave this open for the time being. One of my tickets is researching the slow loading issues and based on what I've found so far it very well could be an expo issue. Apparently running from expo means that our app is requesting images from the expo server (like a web page) rather than from our files directly. We can implement an async load on the images so that might help. However since we are detaching from expo soon that might also resolve the issue. Since next sprint we are beginning to move forward with the detachment process it might be best to test it out then so we can see if that fixes our loading issues.

**Comment by Nuni88** [comment]
@bnelson777 I'm actually gonna close this one now, because it looks like it's redundant with the UI changes from IL-66.

**Pull request closed without merging**
