### PR TITLE
About screen icon updated

### PR DESCRIPTION
**Pull request by bnelson777**
-Updated About screen icon and realigned github/pdx.edu icons

Testing steps
1. Open app and open dev mode
2. Access About page and ensure main icon shows new icon and the icons are aligned properly

image-1

### CODE REVIEW

**Review by vanctran — APPROVED** [review]
Looking good on iOS

**Comment by joewetton** [comment]
Maybe replace all rights reserved with MIT ? I’m not sure idly team reserves all rights.

**Comment by bnelson777** [comment]
Just updated it to say "Powered by id.ly team, MIT license." Does that seem too clunky? We could also just shorten it and say "Powered by id.ly team" without even mentioning the license.

**Comment by joewetton** [comment]
Yeah that sounds better.

**Review by hontatfai — APPROVED** [review]
Works on android emulator. Personally, the image is a little bit bigger.

**Comment by bnelson777** [comment]
I'm going to go ahead an merge this. @hontatfai Feel free to change the image size if you'd like.

**Pull request merged**
