### PR TITLE
IL-111: Mark messages as read after viewing

### PR DESCRIPTION
**Pull request by vanctran**
# Test for IL-111
## Method 1:
1. Start with a new instance of the application.
2. Navigate to the inbox.
3. Click on an unread message (not greyed out).
4. Return to the inbox.
5. The unread should now be greyed out to signify it is read.
## Method 2:
1. Use deep-link to retrieve new message through email.
2. Decrypt the message.
3. Follow method 1.

### CODE REVIEW

**Review by joewetton — APPROVED** [review]
Works as expected on IOS. I'm not sure if we should make messages the user themselves compose as unread since they composed them they technically have read it, but this is not a technical issue more of a design choice. Good work.

**Comment by vanctran** [comment]
Thanks for the heads up @joewetton

**Review by Vancev — APPROVED** [review]
Works on android

**Comment by vanctran** [comment]
Closing for now. Need to update this to match the new filesystem that just got pushed to master.

**Comment by bnelson777** [comment]
Method 1 works as expected but the deep-linked message shows up as read automatically when I decrypt it. Is that the expected behavior? (I vaguely remember talking about this Wednesday I think...)

**Comment by vanctran** [comment]
@bnelson777 I didn't take a try for method 2. I just assumed all messages being decrypted from the lockbox are automatically labeled as unread.

**Review by bnelson777 — APPROVED** [review]
@vanctran Ah ok, well it's showing up as read for me but not a huge deal. I'm ok with merging this then handling it as a bug later.

**Review by Vancev — APPROVED** [review]
Works on android

**Pull request merged**
