### PR TITLE
IL-66: Change elements/icons to use UI library (react-native-elements)

### PR DESCRIPTION
**Pull request by hontatfai**

### CODE REVIEW

**Comment by joewetton** [comment]
@hontatfai can you merge master into this branch? Lots of changes.

**Comment by hontatfai** [comment]
@joewetton already merged the latest master yet on the commit, "fixed conflicts".

**Comment by joewetton** [comment]
I’ll be honest I have no clue what’s changed in this PR, though functionality seems unaffected

**Comment by hontatfai** [comment]
Literally, each component’s UI doesn’t have any big difference, but did many minor layout changes, such as icons, interval, and etc. I also changed the layout of Home page, but it looks not good, so didn’t commit it.😥

**Review by Nuni88 — APPROVED** [review]
Looks good on android.

**Pull request merged**
