### PR TITLE
IL-127: Store/Retrieve Private Keys in Sensitive Info Package

### PR DESCRIPTION
**Pull request by Nuni88**
- Private keys and public keys are now added to sensitive storage in create_card. Public keys are also stored in card object.
- Decrypt message in lockbox has been modified to get private keys from sensitive storage based on matching public key.
- Clear data function has been updated to remove keys from sensitive storage. The function clears an arbitrary number of keys for simplicity and because it is ultimately a dummy function.

Testing:
1. Clear data and reload the app.
2. Go to wallet and create a new card.
3. Send a message from the new card and select email when it appears in lockbox.
4. Open the link from email and observe that it is added to your messages.

### CODE REVIEW

**Review by vanctran — CHANGES_REQUESTED** [review]
There is an issue on iOS:
Adding a card right after loading the application works. However, adding a card after clearing all data does not work.

**Comment by Nuni88** [comment]
@vanctran Do you mean clearing the data and trying to add a card without reloading first? If so, I think that's just a matter of not having the functionality for a first card without dummy data, which is something being added in one of Joe's tickets this sprint. As long as clearing the data, reloading (to get the dummy data loaded in), and then adding cards works, then it should be fine since we're not keeping the clear data function anyway.

**Comment by bnelson777** [comment]
The message doesn't seem to be coming through for me, just getting a timestamp in the message thread. Also, it's created a whole new thread for the same contact rather than add to the current thread, is that an issue that goes along with the first-case ticket scenario?

img_4563

img_4564

**Comment by vanctran** [comment]
@Nuni88 in that case then it works for me. I agree. This isn't an issue we would have to deal with because we're removing that functionality soon.

**Review by vanctran — APPROVED** [review]

**Comment by Nuni88** [comment]
@bnelson777 I was getting the double thread issue when I was testing too, but I'm not completely sure what causes that. I couldn't reliably test the deep linking, so I was testing with manual decryption, but I wasn't sure if that was the problem or not. @vanctran Are you getting the double thread issue?

**Comment by vanctran** [comment]
Just tested it and yes, I am currently getting these issues. My apologies, I believe I was following testing procedures for another PR while on your branch. I'm only getting the timestamp as well.

**Comment by joewetton** [comment]
Please don't merge this ticket for the time being

**Comment by Nuni88** [comment]
Oh, I think I realized the problem. I think it's a problem with the testing method. Does anyone have two phones they could test with? The card the message is being sent to currently is a dummy card, which means it has no private key saved to do the decryption, so the message is set to null because the decryption fails. There might also be some minor async issues in the code that I'll try to work out, but if someone is able to test with two phones, that would be great.

**Comment by joewetton** [comment]
With 2 devices, can't get a messages to decrypt.

**Comment by joewetton** [comment]
We have a lot of branches open involving the lockbox component, let's wait on merging this one.

**Comment by joewetton** [comment]
Adapted @Nuni88 changes into a new branch with latest master... please test that one. IL-127-1

**Pull request closed without merging**
