### PR TITLE
Il-18: Create card screen

### PR DESCRIPTION
**Pull request by ad25**
Create card screen

* Created layout for screen with buttons for add/cancel, section for avatar, form section with add attribute at the bottom.
* Added state required to handle input of form.
* Added the ability to add new fields to form.
* Added entry into Home and index for this component.

### CODE REVIEW

**Review by vanctran — CHANGES_REQUESTED** [review]
line 17-23 inside app/index.js

There is currently git markup in there that needs to be removed

**Review by vanctran — APPROVED** [review]

**Comment by vanctran** [comment]
Works great on Expo. Had no issues adding user-defined attributes.

**Comment by joewetton** [comment]
Missing some functionality added features to the backlog
https://ssid-psu-capstone.atlassian.net/browse/IL-47
https://ssid-psu-capstone.atlassian.net/browse/IL-48

**Review by hontatfai — COMMENTED** [review]
simple layout works on Android emulator, but the adding new card is not implemented
test

**Comment by joewetton** [comment]
Actual addition of the card will be handled in ticket next sprint https://ssid-psu-capstone.atlassian.net/browse/IL-34

**Comment by joewetton** [comment]
Added small UI behavior tweaks and keyboard spacer so you can see when you type an attribute.

**Review by joewetton — APPROVED** [review]

**Pull request merged**
