### PR TITLE
IL-98 : Replace expo component from Scan

### PR DESCRIPTION
**Pull request by hontatfai**
I tried to manual link the RN-camera without changed the directory name, but it always reported errors (tried the solutions, and figured out the errors for few hours, but doesn't work so I gave up and changed the directory name 'idly'). In addition, because I tested the scan in the emulator, I am not sure that can it scan the qrcode so far.

### CODE REVIEW

**Comment by ad25** [comment]
Getting errors when executing react-native run-android on Windows. > java.io.IOException: Could not delete path 'C:\ . . . . \id.ly\node_modules\react-native-camera\android\build\generated\source\buildConfig\release\com'.

**Comment by Nuni88** [comment]
@ad25 You should be able to just delete that build folder and run it again since it rebuilds after that. I think the problem just comes from builds of different branches.

**Comment by ad25** [comment]
@Nuni88 Thanks. Tried it off a fresh clone this time. Each time I remove a folder a new one comes up with no end in sight.

**Comment by hontatfai** [comment]
Oops, I forgot to mention that I update the RN-camera to 1.0.0, so probably need to delete the node_modules before you run rative. or for android studio,  you can clean project and rebuild it.

**Pull request closed without merging**
