### PR TITLE
IL-134: Fixed Home bug (pic/text too big on SE/5S screen layout)

### PR DESCRIPTION
**Pull request by hontatfai**

### CODE REVIEW

**Review by joewetton — CHANGES_REQUESTED** [review]
Getting a strange pink outline instead of previous design. Is this intentional?
screen shot 2018-05-29 at 6 53 19 am

**Comment by hontatfai** [comment]
@joewetton 😂that was an accident, when I fixed the overlap of the card button container, which you pointed out on the ticket IL-126, I changed its color to measure the size.

**Comment by joewetton** [comment]
@hontatfai haha good stuff, thanks!

**Review by joewetton — APPROVED** [review]

**Comment by joewetton** [comment]
screen shot 2018-05-29 at 9 28 11 am

**Comment by joewetton** [comment]
Gonna go ahead and merge this since the bug affects IOS SE/5S devices. Good work @hontatfai

**Comment by joewetton** [comment]
@hontatfai sorry to be a stickler, any chance we can move the right text up a little? so it's more centered with the portrait?
screen shot 2018-05-29 at 9 40 23 am 1

**Comment by hontatfai** [comment]
@joewetton no problem, already aligned to center.

**Pull request merged**
