### PR TITLE
IL-98 & 116: Replace expo component from Scan and Permissions with camera

### PR DESCRIPTION
**Pull request by hontatfai**
Updated the RN-camera version, and added the RN-permissions.

### CODE REVIEW

**Review by ad25 — APPROVED** [review]
Works great on android.

**Comment by vanctran** [comment]
Getting linking issues on iOS. I'll try to see if it's a problem on my side.

**Comment by bnelson777** [comment]
I think I'm having the same linking issues as @vanctran (active discussion in #teamios). Will keep working on it to try and get it to work.

**Comment by joewetton** [comment]
I spent a good amount of hours last night trying to get this thing to work on IOS, still no dice.

**Comment by joewetton** [comment]
We took code that worked on this branch and put in joe-camera branch, closing.

**Pull request closed without merging**
