### PR TITLE
IL-4

### PR DESCRIPTION
**Pull request by ad25**
* Added actions and reducers for getMessage
* Added initial processing for messages from messages.json
* Modified cards.json to include a portrait field for objects which stores a base64 encoded image
* Added messages.json as a way to store messages persistently
* Added 3 components: Inbox, InboxItem, and Portrait
* Included Inbox in index.js
* Added an entry into the router for the inbox scene

### CODE REVIEW

**Review by joewetton — CHANGES_REQUESTED** [review]
screen shot 2018-04-10 at 8 22 42 am

**Review by Nuni88 — APPROVED** [review]
Works for me on android.

**Review by hontatfai — COMMENTED** [review]
It works on android, but it reports error on iOS.
ios_test
android_v26_test

**Comment by joewetton** [comment]
Found the line 56 InboxItem.js remove <Portrait cardId={this.props.cardId} /> works on IOS
screen shot 2018-04-10 at 11 15 19 am

**Review by bnelson777 — APPROVED** [review]
Works on the ios expo simulator for me so I'm going to approve it. Sounds like we know where the bug is for ios at least so we can either work on that later or just make the change now and an android tester can make sure it works for them.
screen shot 2018-04-10 at 11 20 55 am

**Pull request merged**
