### PR TITLE
IL-20: removed contact references

### PR DESCRIPTION
**Pull request by joewetton**
- removed contact data structure and json
- since rolodex and wallet will be combined into a new single component, I didn't bother to update rolodex references to this item

### CODE REVIEW

**Comment by ad25** [comment]
No new errors or warnings here on android. App works for me.

**Comment by bnelson777** [comment]
screen shot 2018-04-12 at 6 37 28 pm

I'm getting the above error, however it's easily fixable if you import CLEAR_ALL under reducers/index.js (I tried it myself and it works if that change is made).

**Review by bnelson777 — CHANGES_REQUESTED** [review]
Let's try re-adding CLEAR_ALL to the reducers index.js and just verify that small change doesn't break android.

**Review by bnelson777 — APPROVED** [review]

**Comment by bnelson777** [comment]
working now 👍

**Review by Vancev — APPROVED** [review]
Everything looks good for android

**Pull request merged**
