### PR TITLE
IL-34: CRUD functions & create message message working & decrypt

### PR DESCRIPTION
**Pull request by joewetton**
Implemented the redux functionally for edit, delete and add.

### CODE REVIEW

**Comment by joewetton** [comment]
img_643c18033640-1

Long press on a particular card to get to it

**Comment by joewetton** [comment]
I've decided to hold off on allowing editing of a card, as it will involve quite a bit of time to write and we aren't even sure if we plan to allow users to do this. Will add to backlog we can decide on implementing this later. For now delete and add should be working. And this should be enough to ensure our redux state is being handled properly.

**Review by Nuni88 — CHANGES_REQUESTED** [review]
Getting errors for long press on wallet/rolodex and when going to create message screen on android.

delete error

create message error

**Review by bnelson777 — APPROVED** [review]
Tested new message functionality, new message appears in inbox works for ios 👍 Long press works fine for me

**Comment by joewetton** [comment]
Fixed one error, the other is because android doesn't have a native share sheet like IOS, will have to revisit when we detach and can use native packages like this one https://stackoverflow.com/questions/35052767/whats-the-equivalent-of-actionsheetios-in-android

**Review by ad25 — APPROVED** [review]
Tested on android device.

Create Message
Other than the long press issue, message shows up in inbox after creating message w/ correct date and message body.
No issue with create message drop down pickers on android.

**Comment by bnelson777** [comment]
@ad25 @Nuni88  Does the rest of the functionality work on Android if you don't use the long press? It might be something that we will have to develop for each platform separately if not.

**Comment by ad25** [comment]
@bnelson777 Can confirm on android that cards are removed and the screen updates when functions are called directly instead of using the IOS ActionSheet.

**Comment by joewetton** [comment]
So.. going to merge this and create a ticket to implement an action type menu for android somewhere along the line.. I don't think there is much other solution until we detach.

**Comment by joewetton** [comment]
https://ssid-psu-capstone.atlassian.net/browse/IL-55

**Pull request merged**
