### PR TITLE
fix: Message Item not showing '>'

### PR DESCRIPTION
**Pull request by ad25**
Test instructions:
	npm install
	react-native link
	react-native run-android
	or
	react-native run-ios

- Should be able to run react-native link without error
- Far right of message should be a '>'. not Kanji or a crossed out box
linkissue

### CODE REVIEW

**Review by bnelson777 — APPROVED** [review]
Thanks for taking initiative and fixing this! Works great on ios, no longer getting the warning and the ">" now appears.

**Review by vanctran — CHANGES_REQUESTED** [review]
I don't think it's a good idea to move the directory from id.ly to id/ly

This is going to cause a lot of confusion later

**Review by Nuni88 — APPROVED** [review]
Inbox looks good on android and shows the arrow again. I agree with Van about the directory change though.

**Comment by bnelson777** [comment]
If the concern is about the file structure changing we could wait to merge this one after talking about it either Tuesday or Wednesday. Might not look pretty but if it helps fix compilation issues for someone I'd rather take something that we know works rather than spend time digging for another solution if we don't have to.

**Review by hontatfai — COMMENTED** [review]
I tried to changed the directory to id/ly too, but when I deleted android/iso files, and did 'react-native eject', the issue is still here. It is fine to do this way in our current development, but not good for the application update and lifecycle. Thus, I just changed the name and rebuild the android/iso as well.

**Comment by ad25** [comment]
I noticed that branden-eject did not have issues with directories and linking. This fix is just adapting to master. If its possible to switch to branden-eject then maybe that would be a more acceptable solution? I agree, however, that this should be discussed.

**Pull request closed without merging**
