### PR TITLE
IL-33: Get bluetooth react native package working

### PR DESCRIPTION
**Pull request by Vancev**
- Added the package 'react-native-ble-plx'

- Allows to scan for bluetooth devices. Can only scan for bluetooth low energy devices, so devices that do not support BLE will not be picked up.

To test:
Find a BLE compatible device and turn its bluetooth on. Open the app and click on "[dev] Bluetooth". The app will start scanning for bluetooth devices and a popup will show the found device(s). If you do not see a popup, then no devices were found.

### CODE REVIEW

**Comment by vanctran** [comment]
@bnelson777 this one is up to you for iOS. I can only run through emulator at the moment.

**Comment by ad25** [comment]
- Made sure that my phones Bluetooth was on.
- Made sure that I could see the other Bluetooth device from settings.
Getting an error upon entering [dev] bluetooth.
TypeError: Cannot read property 'createClient' of undefined.

Here is the warning that I get when I enter [dev] bluetooth with the phones bluetooth disabled. Seems related.
bluetooth warning

**Comment by bnelson777** [comment]
Tried to run this last night on my phone but had some issues getting my phone to work with the request, I'm guessing it has something to do with the new module so probably just have to do some combination of install/merge/relink. Not sure if I'll have time to test this before the retrospective but I'll try my best!

**Comment by Vancev** [comment]
@ad25  I had that same error when I was trying to set the module up. I fixed it by making the MainApplication file like this:

at the top: import com.polidea.reactnativeble.BlePackage;

and in public class MainApplication having:

    '@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        new MainReactPackage(),
        new BlePackage()
      );
}`

I pushed those changes up so it may be something else causing the problem. But they could have been removed by npm install or something else. Can you check your MainApplication file and see if its like above?

**Pull request closed without merging**
