### PR TITLE
IL-124: Resend Message from MessageThread

### PR DESCRIPTION
**Pull request by vanctran**
# New Feature:
Users are now able to resend messages from the message thread by long pressing (press and holding) a message bubble.

# Testing:
1. Open up the message thread of any message from the inbox.
2. Long press (press and hold on) a message you wish to resend.
3. Confirm that a lockbox screen pops up with data
4. Send out that message
5. Retrieve message from email and decrypt to confirm the message is correct.

### CODE REVIEW

**Review by bnelson777 — APPROVED** [review]
Works for ios. 👍 One thing we may want to add to the backlog is updating the timestamp for resent messages. Not a huge deal but might make more sense

**Comment by vanctran** [comment]
@bnelson777 I thought about having it use the current timestamp, but then the messages would be out of order if you resend a message that was meant to be in between 2 others.

**Comment by Vancev** [comment]
Nothing happens on android when long pressing.

**Comment by joewetton** [comment]
@vanctran can we just make it so you long hold the message so it takes you directly to the lockbox instead of pulling up the Action menu? I know we will loose ability to copy text but it doesn't work on android anyway so I'd rather just have resend ability on both platforms.

**Review by hontatfai — COMMENTED** [review]
I tried few time, it popped up the encrypted msg, but didn't resend the message when I long pressed a message.
image

**Comment by joewetton** [comment]
@hontatfai that's the expected behavior

**Comment by hontatfai** [comment]
@joewetton ok, I thought that it would display the resend msg again, or prompted that the msg has resent in the msg thread.

**Review by joewetton — APPROVED** [review]

**Comment by joewetton** [comment]
@hontatfai updated title to "Resend message"

**Comment by hontatfai** [comment]
Another problem is on android, it wont pop up any resend button/alter, a long pressing will send the msg out directly.

**Comment by joewetton** [comment]
Testing notes are out of date, now a longhand press on a message will take you to the lockbox screen where a user can email it out to someone. It should then return them to the thread when they hit done.

**Comment by hontatfai** [comment]
Alright, my bad. I just thought it would be awkward if I resend it by misclick.

**Comment by joewetton** [comment]
yeah I understand, but being taken to that screen doesn't resend the message until the user emails it or copies the link. So if user long presses by accident, they can just click Done and there is no consequence.

**Comment by vanctran** [comment]
Updated the test instructions. From the looks of it, you are getting expected behavior 😀 @hontatfai

**Review by hontatfai — APPROVED** [review]

**Pull request merged**
